### ISSUE TITLE
Error: Not found: /undefined/rooms

### ISSUE THREAD

**Issue by JimLynchCodes** [0xLaurens/chatr#37]
Hi!

When I try to run the frontend and backend locally is seems like everything starts up fine.

When I try to go to the page http://localhost:5173/ though I see this below error in fronted console, and then the chat on the next page doesn't work...

```
Error: Not found: /undefined/rooms
    at resolve (/Users/jim/Forked-Git-Projects/chatr/client/node_modules/@sveltejs/kit/src/runtime/server/respond.js:397:13)
    at resolve (/Users/jim/Forked-Git-Projects/chatr/client/node_modules/@sveltejs/kit/src/runtime/server/respond.js:246:5)
    at #options.hooks.handle (/Users/jim/Forked-Git-Projects/chatr/client/node_modules/@sveltejs/kit/src/runtime/server/index.js:41:55)
    at Module.respond (/Users/jim/Forked-Git-Projects/chatr/client/node_modules/@sveltejs/kit/src/runtime/server/respond.js:243:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by 0xLaurens** [comment]
Hello @JimLynchCodes,
I think I resolved the issue, if you pull the main branch you should be able to run without any issues. I believe it was an bug related to a trailing slash -> localhost:3000/ in the env would become localhost:3000//rooms.
LMK if this solved your issue!

**Comment by JimLynchCodes** [comment]
@0xLaurens Yep, it's working for me now.

Thanks!!
